"""add sku to products

Revision ID: 2ce51a10ff8b
Revises: c54d3a0d6e4c
Create Date: 2026-06-13 20:09:54.374260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ce51a10ff8b'
down_revision: Union[str, Sequence[str], None] = 'c54d3a0d6e4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('sku', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'sku')
    # ### end Alembic commands ###
