"""remove sku

Revision ID: a4da1e8f560e
Revises: 2ce51a10ff8b
Create Date: 2026-06-13 20:13:16.287288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4da1e8f560e'
down_revision: Union[str, Sequence[str], None] = '2ce51a10ff8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'sku')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('sku', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
